Add scripts to output contacts and stakeholders CSVs
cisagov/cyhy-reports pull request #108
Opened 2024-01-30 19:44 UTC by dav3r

#  #

## 🗣 Description ##

This PR adds two new scripts (`cyhy-contacts` and `cyhy-stakeholders`) that output CSV data for the contacts and stakeholders in the CyHy database.

## 💭 Motivation and context ##

These scripts are very similar to those in [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) (see [here](https://github.com/cisagov/ncats-webd/blob/develop/ncats_webd/blueprints/stakeholders/contacts.py) and [here](https://github.com/cisagov/ncats-webd/blob/develop/ncats_webd/blueprints/stakeholders/stakeholders_info.py)), but those scripts were designed to be run as part of a web-based dashboard.  I modified them slightly so that they can be easily run from a shell.

## 🧪 Testing ##

I confirmed that these new scripts run as expected via a Docker container, which is the primary way that they are going to be used.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Post-merge checklist ##

- [ ] Notify the CyHy team that these new scripts are available for their use.

2024-01-30 20:42 UTC, dv4harr10 commented
Hi Team, one medium severity issue at extras/create_snapshots_reports_scorecard.py line 815 and 819, the subprocess function has shell=True, which can allow a malicious actor to execute commands. Suggestion is to set shell=False instead.

2024-01-30 20:58 UTC, jsf9k commented
> Hi Team, one medium severity issue at extras/create_snapshots_reports_scorecard.py line 815 and 819, the subprocess function has shell=True, which can allow a malicious actor to execute commands. Suggestion is to set shell=False instead.

@dv4harr10 - I think [you already reported this issue](https://github.com/cisagov/cyhy-reports/issues/102).

2024-01-30 20:59 UTC, jsf9k approved these changes

2024-01-30 21:04 UTC, dv4harr10 commented
Hi Team, one medium severity issue at extras/create_snapshots_reports_scorecard.py line 815 and 819, the subprocess function has shell=True, which can allow a malicious actor to execute commands. Suggestion is to set shell=False instead.

@dv4harr10 - I think https://github.com/cisagov/cyhy-reports/issues/102. In any event, it has nothing to do with the changes in this PR.

Ok Great, otherwise looks fine to me.

2024-01-30 21:04 UTC, dv4harr10 approved these changes

2024-01-31 23:28 UTC, mcdonnnj requested changes
Overall this looks like strong work 💪💪💪 I have some feedback items for your consideration.

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
> +    for doc in all_request_docs:
Is this doable? It just seems silly to assign the result to a variable and then iterate over it separately. I added a comment just to be as explanatory as the variable name.

```suggestion
    # Iterate through all request documents
    for doc in db.RequestDoc.find().sort("_id", 1):
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
> +    all_request_docs = db.RequestDoc.find().sort("_id", 1)
If my previous suggestion is viable.

```suggestion
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
> +                "Org Retired": doc.get("retired", False),
We could technically define this portion before the loop on contacts and do a `row.update()` for each contact but that might be an unnecessary micro-optimization.

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
> +                "{}".format(org["_id"]),
Is there a reason we're using `format()` for all of these when it's just doing string conversion at most?

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
> +    for org in stakeholders:
Same thought about seemingly unnecessary variable assignment.

```suggestion
    for org in db.RequestDoc.find({"_id": {"$in": stakeholder_ids}}).sort([("_id", 1)]):
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
> +#!/usr/bin/env python
I know this is cribbed but we shouldn't be doing this anymore as the script in `bin/` negates the need.

```suggestion
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
> +    main()
I know this is cribbed but we shouldn't be doing this anymore as the script in `bin/` negates the need.

```suggestion
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
> +#!/usr/bin/env python
I know this is cribbed but we shouldn't be doing this anymore as the script in `bin/` negates the need.

```suggestion
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
> +    main()
I know this is cribbed but we shouldn't be doing this anymore as the script in `bin/` negates the need.

```suggestion
```

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/contacts/contacts.py
I would prefer that this file is not executable as it should never be run directly with the other changes I've suggested.

2024-01-31 23:28 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
I would prefer that this file is not executable as it should never be run directly with the other changes I've suggested.

2024-02-02 19:55 UTC, dav3r commented on cyhy_report/contacts/contacts.py
I removed the executable bit in https://github.com/cisagov/cyhy-reports/pull/108/commits/75eea8b5f734d664fdb21e57b4ce12b75e32fef2.

2024-02-02 19:55 UTC, dav3r commented on cyhy_report/stakeholders/stakeholders.py
I removed the executable bit in https://github.com/cisagov/cyhy-reports/pull/108/commits/75eea8b5f734d664fdb21e57b4ce12b75e32fef2.

2024-02-02 20:58 UTC, dav3r commented on cyhy_report/stakeholders/stakeholders.py
> +                "{}".format(org["_id"]),
Nope- I removed the `format()` jazz in https://github.com/cisagov/cyhy-reports/pull/108/commits/4317bc59c5310a350f30c10f59ae8bea6ed16378.

2024-02-02 21:11 UTC, dav3r commented on cyhy_report/contacts/contacts.py
> +                "Org Retired": doc.get("retired", False),
Since you mentioned it, why not? 😄  Please see https://github.com/cisagov/cyhy-reports/pull/108/commits/befbd442d5570cd044f13273fa85fd8860c45fc4.

2024-02-05 18:49 UTC, mcdonnnj requested changes
Thank you for resolving my previous feedback. This is into nitpick turf but I'd really like it if we had docstrings for any functions in the new subpackages. This is consistent with any newer Python project of ours because of the inclusion of the [flake8-docstrings](https://github.com/pycqa/flake8-docstrings) plugin in our linting configuration. I know we cannot use our normal linting configuration due to the reliance on Python 2 for this project but I would like the code to be as close to passing our usual linter selection as reasonably possible.

2024-02-05 19:27 UTC, dav3r commented
> Thank you for resolving my previous feedback. This is into nitpick turf but I'd really like it if we had docstrings for any functions in the new subpackages.

I added docstrings in https://github.com/cisagov/cyhy-reports/pull/108/commits/379a045a3e7ccc77d9632403e1723daf4ca3dd6c - please take a look and let me know if you have any other concerns.

2024-02-05 19:31 UTC, mcdonnnj approved these changes
Strong work 💪💪💪

2024-02-05 19:31 UTC, mcdonnnj commented on cyhy_report/stakeholders/stakeholders.py
> +    """Return a dictionary with first snapshot times for a list of CyHy owner IDs
```suggestion
    """Return a dictionary with first snapshot times for a list of CyHy owner IDs.
```

2024-02-05 19:35 UTC, merged